"""empty message

Revision ID: a36310f80e18
Revises: b489630c78f3
Create Date: 2025-03-19 22:07:56.891387

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a36310f80e18'
down_revision = 'b489630c78f3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('env_requirement',
    sa.Column('id_requirement', sa.Integer(), nullable=False),
    sa.Column('sun_exposure', sa.Enum('Full_sun', 'Partial_shade', 'Full_shade', name='sunexposure'), nullable=False),
    sa.Column('min_temp', sa.Float(), nullable=False),
    sa.Column('max_temp', sa.Float(), nullable=False),
    sa.Column('frost_tolerance', sa.Boolean(), nullable=False),
    sa.Column('id_crop', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_crop'], ['crop.id'], ),
    sa.PrimaryKeyConstraint('id_requirement')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('env_requirement')
    # ### end Alembic commands ###
