"""empty message

Revision ID: b489630c78f3
Revises: af03d27feea1
Create Date: 2025-03-15 20:47:20.143526

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b489630c78f3'
down_revision = 'af03d27feea1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('planting_calendar',
    sa.Column('id_calendar', sa.Integer(), nullable=False),
    sa.Column('planting_date_start', sa.Date(), nullable=False),
    sa.Column('planting_date_end', sa.Date(), nullable=True),
    sa.Column('transplant_date_start', sa.Date(), nullable=True),
    sa.Column('transplant_date_end', sa.Date(), nullable=True),
    sa.Column('estimated_harvest_start_date', sa.Date(), nullable=True),
    sa.Column('estimated_harvest_end_date', sa.Date(), nullable=True),
    sa.Column('id_crop', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_crop'], ['crop.id'], ),
    sa.PrimaryKeyConstraint('id_calendar')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('planting_calendar')
    # ### end Alembic commands ###
